import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ShieldAlert, MapPin, Clock, MessageSquare, ShieldCheck, Activity } from "lucide-react";

export default function CitizenAlerts() {
  const [adminAlerts, setAdminAlerts] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchAlerts = async () => {
    try {
      const token = localStorage.getItem("token");
      if (!token) return;
      const res = await fetch(`${import.meta.env.VITE_BACKEND_URL}/api/notifications`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const data = await res.json();
      if (data.success && data.notifications) {
        const isAutoSystemPing = (msg) => msg?.includes("COMMUNITY SAFETY ALERT");
        
        // Filter for Verified Broadcasts sent by Admin
        setAdminAlerts(data.notifications.filter(n => n.type === "citizen_alert" && !isAutoSystemPing(n.message)));
      }
    } catch (err) {
      console.error("Failed to fetch admin alerts", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
    
    const handler = () => fetchAlerts();
    window.addEventListener("new-notification-received", handler);
    return () => window.removeEventListener("new-notification-received", handler);
  }, []);

  return (
    <div className="p-6 md:p-10 font-sans min-h-full bg-[#f8fafc]">
      <div className="mb-10">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-indigo-500/10 text-indigo-600 font-bold text-[10px] mb-4 uppercase tracking-widest border border-indigo-500/20">
          <ShieldAlert className="h-4 w-4" /> Official Transmissions
        </div>
        <h1 className="text-4xl md:text-5xl font-black mb-4 text-slate-900 tracking-tighter uppercase">
          Admin <span className="text-indigo-600">Alerts</span>
        </h1>
        <p className="text-slate-500 max-w-2xl leading-relaxed text-sm font-medium">
          Official safety broadcasts and verified crime reports generated by the administrative command center.
        </p>
      </div>

      {loading ? (
        <div className="flex justify-center items-center py-24">
           <Activity className="h-8 w-8 text-indigo-600 animate-spin" />
        </div>
      ) : adminAlerts.length === 0 ? (
        <div className="bg-white border border-slate-200 rounded-[32px] p-16 text-center shadow-[0_8px_30px_rgb(0,0,0,0.04)]">
          <div className="w-20 h-20 bg-slate-50 rounded-[20px] flex items-center justify-center mx-auto mb-6 border border-slate-100">
             <ShieldCheck className="h-10 w-10 text-slate-400" />
          </div>
          <h3 className="text-xl font-black text-slate-900 mb-2 uppercase tracking-tight">Zero Active Alerts</h3>
          <p className="text-sm text-slate-500 font-medium max-w-md mx-auto">
            The community is currently secure. There are no active official broadcasts from the administration.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-6">
          {adminAlerts.map(alert => (
            <div key={alert._id} className={`bg-white border-l-[6px] ${!alert.isRead ? 'border-l-rose-500 bg-rose-50/10' : 'border-l-indigo-500'} border-y border-r border-slate-200 rounded-r-[24px] rounded-l-[12px] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] hover:shadow-[0_8px_30px_rgb(0,0,0,0.08)] transition-all group`}>
              <div className="flex justify-between items-start mb-4">
                 <div className="flex items-center gap-3">
                    <div className={`p-2.5 rounded-[12px] ${!alert.isRead ? 'bg-rose-100 text-rose-600' : 'bg-indigo-100 text-indigo-600'}`}>
                        <MessageSquare className="h-5 w-5" />
                    </div>
                    <div className="flex flex-col">
                        <span className={`text-[10px] font-black uppercase tracking-widest ${!alert.isRead ? 'text-rose-600' : 'text-indigo-600'}`}>
                          {!alert.isRead ? 'Urgent Alert' : 'Archived Broadcast'}
                        </span>
                        {alert.crimeId && alert.crimeId.crimeType && (
                          <span className="text-[12px] font-bold text-slate-400 uppercase tracking-widest">
                             {alert.crimeId.crimeType}
                          </span>
                        )}
                    </div>
                 </div>
                 <span className="text-[10px] font-bold text-slate-400 flex items-center gap-1.5 uppercase tracking-wider bg-slate-50 px-3 py-1.5 rounded-full border border-slate-200">
                   <Clock size={12}/> {new Date(alert.createdAt).toLocaleString()}
                 </span>
              </div>
              <p className="text-base font-bold text-slate-800 leading-relaxed max-w-4xl mt-4 mb-2">
                {alert.message}
              </p>
              {alert.crimeId && alert.crimeId.title && (
                <div className="mt-8 p-5 bg-[#F7F9FC] rounded-[16px] border border-slate-200 flex flex-col md:flex-row justify-between md:items-center gap-4 group-hover:border-indigo-100 transition-colors">
                  <div>
                      <p className="text-[10px] font-black uppercase tracking-widest text-indigo-500 mb-1.5 flex items-center gap-1">
                          <Activity size={10} /> Attached Intelligence Report
                      </p>
                      <p className="text-sm font-black text-slate-900 mb-1">{alert.crimeId.title}</p>
                      <p className="text-xs text-slate-500 flex items-center gap-1 font-medium"><MapPin size={12}/> {alert.crimeId?.location?.address || "Location unavailable"}</p>
                  </div>
                  <Link to={`/citizen/tracking`} className="px-5 py-2.5 bg-white border border-slate-200 text-slate-700 rounded-[12px] text-[10px] font-black uppercase tracking-widest hover:bg-slate-50 hover:text-indigo-600 hover:border-indigo-200 transition-all shrink-0 shadow-sm">
                     Track Incident
                  </Link>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
