import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ShieldAlert, MapPin, Clock, MessageSquare, ShieldCheck, Activity, ChevronsLeft, ChevronLeft, ChevronRight, ChevronsRight } from "lucide-react";

export default function CitizenAlerts() {
  const [adminAlerts, setAdminAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [currentPage, setCurrentPage] = useState(1);
  const [alertsPerPage] = useState(5);

  const fetchAlerts = async () => {
    try {
      const token = localStorage.getItem("token");
      if (!token) return;
      const res = await fetch(`${import.meta.env.VITE_BACKEND_URL}/api/notifications`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const data = await res.json();
      if (data.success && data.notifications) {
        const isAutoSystemPing = (msg) => msg?.includes("COMMUNITY SAFETY ALERT");
        
        // Filter for Verified Broadcasts sent by Admin
        setAdminAlerts(data.notifications.filter(n => n.type === "citizen_alert" && !isAutoSystemPing(n.message)));
      }
    } catch (err) {
      console.error("Failed to fetch admin alerts", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
    
    const handler = () => fetchAlerts();
    window.addEventListener("new-notification-received", handler);
    return () => window.removeEventListener("new-notification-received", handler);
  }, []);

  // Pagination logic
  const indexOfLastAlert = currentPage * alertsPerPage;
  const indexOfFirstAlert = indexOfLastAlert - alertsPerPage;
  const currentAlerts = adminAlerts.slice(indexOfFirstAlert, indexOfLastAlert);
  const totalPages = Math.ceil(adminAlerts.length / alertsPerPage);

  const paginate = (pageNumber) => setCurrentPage(pageNumber);

  const goToFirstPage = () => setCurrentPage(1);
  const goToLastPage = () => setCurrentPage(totalPages);

  return (
    <div className="p-6 md:p-10 font-body min-h-full bg-primary-dark text-text-primary">
      <div className="mb-10 animate-fade-in">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-accent-gold/10 text-accent-gold font-bold text-[10px] mb-4 uppercase tracking-widest border border-accent-gold/20">
          <ShieldAlert className="h-4 w-4" /> Official Transmissions
        </div>
        <h1 className="text-4xl md:text-5xl font-bold mb-4 text-text-primary tracking-tighter uppercase font-heading">
          Admin <span className="text-accent-gold">Alerts</span>
        </h1>
        <p className="text-text-secondary max-w-2xl leading-relaxed text-sm font-medium">
          Official safety broadcasts and verified crime reports generated by the administrative command center.
        </p>
      </div>

      {loading ? (
        <div className="flex justify-center items-center py-24">
           <Activity className="h-8 w-8 text-accent-gold animate-spin" />
        </div>
      ) : adminAlerts.length === 0 ? (
        <div className="ct-card p-16 text-center animate-fade-in">
          <div className="w-20 h-20 bg-primary-dark rounded-[20px] flex items-center justify-center mx-auto mb-6 border border-border-subtle shadow-xl">
             <ShieldCheck className="h-10 w-10 text-text-secondary/30" />
          </div>
          <h3 className="text-xl font-bold text-text-primary mb-2 uppercase tracking-tight font-heading">Zero Active Alerts</h3>
          <p className="text-sm text-text-secondary font-medium max-w-md mx-auto">
            The community is currently secure. There are no active official broadcasts from the administration.
          </p>
        </div>
      ) : (
        <>
          <div className="grid grid-cols-1 gap-6">
            {currentAlerts.map((alert, idx) => (
              <div 
                key={alert._id} 
                className={`bg-secondary-dark border-l-[6px] ${!alert.isRead ? 'border-l-danger bg-danger/5' : 'border-l-accent-gold'} border-y border-r border-border-subtle rounded-r-card rounded-l-[12px] p-8 shadow-xl hover:border-accent-gold/30 transition-all group animate-fade-in`}
                style={{ animationDelay: `${idx * 0.1}s` }}
              >
                <div className="flex justify-between items-start mb-4">
                   <div className="flex items-center gap-3">
                      <div className={`p-2.5 rounded-[12px] ${!alert.isRead ? 'bg-danger/20 text-danger' : 'bg-accent-gold/20 text-accent-gold'}`}>
                          <MessageSquare className="h-5 w-5" />
                      </div>
                      <div className="flex flex-col">
                          <span className={`text-[10px] font-bold uppercase tracking-widest ${!alert.isRead ? 'text-danger' : 'text-accent-gold'}`}>
                            {!alert.isRead ? 'Urgent Alert' : 'Archived Broadcast'}
                          </span>
                          {alert.crimeId && alert.crimeId.crimeType && (
                            <span className="text-[12px] font-bold text-text-secondary uppercase tracking-widest mt-0.5">
                               {alert.crimeId.crimeType}
                            </span>
                          )}
                      </div>
                   </div>
                   <span className="text-[10px] font-bold text-text-secondary flex items-center gap-1.5 uppercase tracking-wider bg-primary-dark px-3 py-1.5 rounded-full border border-border-subtle shadow-inner">
                     <Clock size={12}/> {new Date(alert.createdAt).toLocaleString()}
                   </span>
                </div>
                <p className="text-base font-medium text-text-primary leading-relaxed max-w-4xl mt-4 mb-2">
                  {alert.message}
                </p>
                {alert.crimeId && alert.crimeId.title && (
                  <div className="mt-8 p-5 bg-primary-dark/50 rounded-card border border-border-subtle group-hover:border-accent-gold/20 transition-colors">
                    <div>
                        <p className="text-[10px] font-bold uppercase tracking-widest text-accent-gold mb-1.5 flex items-center gap-1">
                            <Activity size={10} /> Attached Intelligence Report
                        </p>
                        <p className="text-sm font-bold text-text-primary mb-1">{alert.crimeId.title}</p>
                        <p className="text-xs text-text-secondary flex items-center gap-1 font-medium"><MapPin size={12}/> {alert.crimeId?.location?.address || "Location unavailable"}</p>
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Professional Pagination */}
          {totalPages > 1 && (
            <div className="mt-10 flex items-center justify-between px-2">
              <div className="text-sm text-text-secondary">
                Showing <span className="font-bold text-accent-gold">{indexOfFirstAlert + 1}</span> to{' '}
                <span className="font-bold text-accent-gold">{Math.min(indexOfLastAlert, adminAlerts.length)}</span> of{' '}
                <span className="font-bold text-accent-gold">{adminAlerts.length}</span> alerts
              </div>
              
              <div className="flex items-center gap-2">
                <button
                  onClick={goToFirstPage}
                  disabled={currentPage === 1}
                  className={`p-2.5 rounded-xl transition-all duration-200 ${
                    currentPage === 1 
                      ? 'opacity-30 cursor-not-allowed bg-secondary-dark/30 text-text-secondary' 
                      : 'bg-secondary-dark border border-border-subtle text-text-secondary hover:border-accent-gold hover:text-accent-gold hover:shadow-lg'
                  }`}
                  title="First Page"
                >
                  <ChevronsLeft size={18} />
                </button>
                
                <button
                  onClick={() => paginate(currentPage - 1)}
                  disabled={currentPage === 1}
                  className={`p-2.5 rounded-xl transition-all duration-200 ${
                    currentPage === 1 
                      ? 'opacity-30 cursor-not-allowed bg-secondary-dark/30 text-text-secondary' 
                      : 'bg-secondary-dark border border-border-subtle text-text-secondary hover:border-accent-gold hover:text-accent-gold hover:shadow-lg'
                  }`}
                  title="Previous Page"
                >
                  <ChevronLeft size={18} />
                </button>
                
                <div className="flex items-center gap-1.5 mx-2">
                  {Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => (
                    <button
                      key={page}
                      onClick={() => paginate(page)}
                      className={`min-w-[40px] h-10 rounded-xl text-sm font-bold transition-all duration-200 ${
                        currentPage === page
                          ? 'bg-accent-gold text-primary-dark shadow-lg shadow-accent-gold/30'
                          : 'bg-secondary-dark border border-border-subtle text-text-secondary hover:border-accent-gold hover:text-accent-gold'
                      }`}
                    >
                      {page}
                    </button>
                  ))}
                </div>
                
                <button
                  onClick={() => paginate(currentPage + 1)}
                  disabled={currentPage === totalPages}
                  className={`p-2.5 rounded-xl transition-all duration-200 ${
                    currentPage === totalPages 
                      ? 'opacity-30 cursor-not-allowed bg-secondary-dark/30 text-text-secondary' 
                      : 'bg-secondary-dark border border-border-subtle text-text-secondary hover:border-accent-gold hover:text-accent-gold hover:shadow-lg'
                  }`}
                  title="Next Page"
                >
                  <ChevronRight size={18} />
                </button>
                
                <button
                  onClick={goToLastPage}
                  disabled={currentPage === totalPages}
                  className={`p-2.5 rounded-xl transition-all duration-200 ${
                    currentPage === totalPages 
                      ? 'opacity-30 cursor-not-allowed bg-secondary-dark/30 text-text-secondary' 
                      : 'bg-secondary-dark border border-border-subtle text-text-secondary hover:border-accent-gold hover:text-accent-gold hover:shadow-lg'
                  }`}
                  title="Last Page"
                >
                  <ChevronsRight size={18} />
                </button>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
